---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: customer002
  namespace: customer002
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/mkokott-aws/gitops-demo-app

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: customer002
  namespace: customer002
spec:
  interval: 1m0s
  path: ./onboarding-namespace-demo/deploy
  prune: false
  serviceAccountName: customer002
  sourceRef:
    kind: GitRepository
    name: customer002

