apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-fieldref
  namespace: secret-area
spec:
  containers:
    - name: test-container
      image: 008309914603.dkr.ecr.eu-west-1.amazonaws.com/env-vars-demo
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
  restartPolicy: OnFailure

